/**
 * TypeScript Declaration Stubs
 * Generated by context-pack scoped analysis
 *
 * This file contains type declarations for external dependencies
 * and internal symbols that were excluded from the scoped pack
 * due to budget constraints.
 */