import type { TsProgramService } from '../../core/ts-program/service.js';
import type { GraphNode } from './graph-builder.js';
import type { RankedNode } from './ranker.js';

export interface StubGenerationResult {
  content: string;
  externalPackages: number;
  internalSymbols: number;
  packages: string[];
  symbols: Array<{
    name: string;
    kind: string;
    path: string;
    reason: string;
  }>;
}

/**
 * StubGenerator creates TypeScript declaration stubs for external dependencies
 * and internal symbols that were excluded due to budget constraints
 */
export class StubGenerator {
  private tsProgramService: TsProgramService;

  constructor(tsProgramService: TsProgramService) {
    this.tsProgramService = tsProgramService;
  }

  /**
   * Generate TypeScript declaration stubs
   */
  async generateStubs(allNodes: GraphNode[], includedNodes: RankedNode[]): Promise<StubGenerationResult> {
    const includedIds = new Set(includedNodes.filter(n => n.included).map(n => n.id));
    const excludedNodes = allNodes.filter(node => !includedIds.has(node.id));

    const externalPackageStubs = new Map<string, Set<string>>();
    const internalSymbolStubs: Array<{
      name: string;
      kind: string;
      path: string;
      reason: string;
    }> = [];

    // Process excluded nodes
    for (const node of excludedNodes) {
      const symbolPath = node.symbol.fqn.path;

      if (this.isExternalPath(symbolPath)) {
        // External dependency - group by package
        const packageName = this.extractPackageName(symbolPath);
        if (packageName) {
          if (!externalPackageStubs.has(packageName)) {
            externalPackageStubs.set(packageName, new Set());
          }
          externalPackageStubs.get(packageName)!.add(node.symbol.fqn.symbol);
        }
      } else {
        // Internal symbol excluded due to budget
        internalSymbolStubs.push({
          name: node.symbol.fqn.symbol,
          kind: this.inferSymbolKind(node.symbol.fqn.symbol),
          path: symbolPath,
          reason: 'budget-excluded'
        });
      }
    }

    // Generate stub content
    const stubSections: string[] = [];

    // Header comment
    stubSections.push(this.generateHeader());

    // External package stubs
    if (externalPackageStubs.size > 0) {
      stubSections.push('// External package stubs');
      for (const [packageName, symbols] of externalPackageStubs) {
        const packageStub = await this.generatePackageStub(packageName, Array.from(symbols));
        stubSections.push(packageStub);
      }
    }

    // Internal symbol stubs
    if (internalSymbolStubs.length > 0) {
      stubSections.push('// Internal symbols (excluded by budget)');
      const internalStub = this.generateInternalSymbolStubs(internalSymbolStubs);
      stubSections.push(internalStub);
    }

    const content = stubSections.join('\n\n').trim();

    return {
      content,
      externalPackages: externalPackageStubs.size,
      internalSymbols: internalSymbolStubs.length,
      packages: Array.from(externalPackageStubs.keys()).sort(),
      symbols: internalSymbolStubs.sort((a, b) => a.name.localeCompare(b.name))
    };
  }

  private generateHeader(): string {
    return `/**
 * TypeScript Declaration Stubs
 * Generated by context-pack scoped analysis
 *
 * This file contains type declarations for external dependencies
 * and internal symbols that were excluded from the scoped pack
 * due to budget constraints.
 */`;
  }

  private async generatePackageStub(packageName: string, symbols: string[]): Promise<string> {
    const stub = [`declare module "${packageName}" {`];

    // Generate stubs for each symbol
    for (const symbol of symbols.sort()) {
      const symbolStub = this.generateSymbolStub(symbol);
      stub.push(`  ${symbolStub}`);
    }

    stub.push('}');
    return stub.join('\n');
  }

  private generateSymbolStub(symbolName: string): string {
    // Generate appropriate stub based on symbol name patterns

    // Interface pattern (starts with I and capital letter)
    if (symbolName.startsWith('I') && symbolName[1]?.toUpperCase() === symbolName[1]) {
      return `export interface ${symbolName} {
    [key: string]: any;
  }`;
    }

    // Class pattern (PascalCase)
    if (symbolName[0]?.toUpperCase() === symbolName[0] && !symbolName.includes('_')) {
      return `export class ${symbolName} {
    constructor(...args: any[]);
    [key: string]: any;
  }`;
    }

    // Type pattern (usually PascalCase but could be anything)
    if (symbolName.endsWith('Type') || symbolName.endsWith('Config') || symbolName.endsWith('Options')) {
      return `export type ${symbolName} = any;`;
    }

    // Enum pattern (PascalCase, often plural or ends with Enum)
    if (symbolName[0]?.toUpperCase() === symbolName[0] && (symbolName.endsWith('s') || symbolName.endsWith('Enum'))) {
      return `export enum ${symbolName} {
    [key: string]: any;
  }`;
    }

    // Function pattern (camelCase or snake_case)
    if (symbolName[0]?.toLowerCase() === symbolName[0]) {
      return `export function ${symbolName}(...args: any[]): any;`;
    }

    // Default to const
    return `export const ${symbolName}: any;`;
  }

  private generateInternalSymbolStubs(symbols: Array<{ name: string; kind: string; path: string; reason: string }>): string {
    if (symbols.length === 0) return '';

    const stub = ['// Internal symbols excluded by budget constraints'];

    // Group by file
    const byFile = new Map<string, typeof symbols>();
    for (const symbol of symbols) {
      if (!byFile.has(symbol.path)) {
        byFile.set(symbol.path, []);
      }
      byFile.get(symbol.path)!.push(symbol);
    }

    for (const [filePath, fileSymbols] of byFile) {
      stub.push(`// From ${filePath}`);

      for (const symbol of fileSymbols) {
        switch (symbol.kind) {
          case 'interface':
            stub.push(`export interface ${symbol.name} { [key: string]: any; }`);
            break;
          case 'class':
            stub.push(`export class ${symbol.name} { constructor(...args: any[]); [key: string]: any; }`);
            break;
          case 'type':
            stub.push(`export type ${symbol.name} = any;`);
            break;
          case 'enum':
            stub.push(`export enum ${symbol.name} { [key: string]: any; }`);
            break;
          case 'function':
            stub.push(`export function ${symbol.name}(...args: any[]): any;`);
            break;
          default:
            stub.push(`export const ${symbol.name}: any;`);
        }
      }

      stub.push('');
    }

    return stub.join('\n');
  }

  private isExternalPath(path: string): boolean {
    return path.includes('node_modules') ||
           path.includes('@types/') ||
           !path.startsWith('src/') && !path.startsWith('./') && !path.startsWith('../');
  }

  private extractPackageName(path: string): string | null {
    // Extract package name from node_modules path
    const nodeModulesMatch = path.match(/node_modules\/(@[^/]+\/[^/]+|[^/]+)/);
    if (nodeModulesMatch) {
      return nodeModulesMatch[1];
    }

    // Extract from @types packages
    const typesMatch = path.match(/@types\/([^/]+)/);
    if (typesMatch) {
      return typesMatch[1];
    }

    return null;
  }

  private inferSymbolKind(symbolName: string): string {
    // Same logic as in Slicer
    if (symbolName.startsWith('I') && symbolName[1]?.toUpperCase() === symbolName[1]) {
      return 'interface';
    }

    if (symbolName[0]?.toUpperCase() === symbolName[0] && !symbolName.includes('_')) {
      return 'class';
    }

    if (symbolName.endsWith('Type') || symbolName.endsWith('Config')) {
      return 'type';
    }

    if (symbolName[0]?.toUpperCase() === symbolName[0] && symbolName.endsWith('Enum')) {
      return 'enum';
    }

    return 'function';
  }
}